### ISSUE TITLE
Figure out resolution order of title patterns

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#1010]
### Description

Given N title pattern which may have overlapping URLs, how do we determine which title pattern should take precedence for which URL.

For example:

URL1 -> TitlePatternA
URL1 -> TitlePatternB

Here, should TitlePatternB take precedence over TitlePatternA?

This can be done in various ways:
1. Chronological order (most recent title pattern beats old title pattern)
2. Size (more specific title pattern that applies to fewer URLs wins a broader title pattern that applies to more URLs)

### Implementation Considerations

- Needs thought

### Deliverable

- Design doc for this
- A working system that makes sense

**Comment by CarsonDavis** [comment]
Solved by the new title resolution rules
