### ISSUE TITLE
Add additional workflow statuses on COSMOS to help the re-indexation process

### ISSUE THREAD

**Issue by bishwaspraveen** [NASA-IMPACT/sde-indexing-helper#1055]
## Description
We might need additional workflow statuses on COSMOS to support re-indexation. The current thought process is to have more linear statuses as shown below:
- Rescraping?
- On Prod, new curation
- On Prod, new quality checks
- On Prod, new quality checks failed
- On Prod, new quality checks minor
- On Prod, Perfect

## Implementation Considerations
Initial discussions documented [here](https://docs.google.com/document/d/1yJegDPNokHFrVKyeOWf8sU9sQuf8DvuQjFANpkalwWs/edit)

We will do this in a two step process, first with some stopgap statuses to get us up and running, then with a full refactor in PI 25.2.

- [sheets](https://docs.google.com/spreadsheets/d/1bpifPuH6hplRjyUJ8_PlJzhspfrVuQ2SKC0heK8LHjc/edit?gid=1886399114#gid=1886399114)
- [document](https://docs.google.com/document/d/1UsM61uqVQkGCWD-mztZeSk-Ob71IKF8iMeSHJ1-oRuo/edit?tab=t.0)

## Deliverable
Needs another session of tech deep dive.

**Comment by CarsonDavis** [comment]
@dhanur-sharma @CarsonDavis to meet to discuss a stopgap solution on Mon Dec 2nd.
