### ISSUE TITLE
Implement ML Tags Backend in COSMOS

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/sde-indexing-helper#1057]
## Implementation Considerations
- two column tag model that can be inherited for many tag uses
- tag for tdamm that inherits the two column tag
- serializer prioritizes the SME column

## Dependencies
depends on #

``` [tasklist]
### Acceptance Criteria
- [ ] Criteria 1
```

**Comment by Kirandawadi** [comment]
Code needed to be refactored due to Delta Urls. Now, this issue is addressed by #1098 
Successfully merging #1103 [Refactor Two Column to work with Delta Urls] will resolve this issue.
