### ISSUE TITLE
Status Button Color Matches

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/sde-indexing-helper#1150]
### Description

Currently, the colors for the status buttons, especially the terminal statuses, to not match. Obviously we won't have full parity, but where there is overlap, we should have color matches.

<img width="931" alt="Image" src="https://github.com/user-attachments/assets/2f5dfb5b-635f-408e-a360-e6e78b72f3cf" />

### Implementation Considerations

- type your first consideration here

### Deliverable

arst

### Dependencies

depends on

**Comment by dhanur-sharma** [comment]
Following [this](https://docs.google.com/spreadsheets/d/1U0kvQDyh_aGbkjM2K9CcdKlRJ6DkBuzFQJslc9QI35w/edit?usp=sharing) color scheme when mapping the statuses.
