### ISSUE TITLE
Delta Urls with a Count of 0 on the Collection List Page Do Not Have Active Link to Delta Urls Page

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/sde-indexing-helper#1154]
### Description

If I’m on the homepage, and I click the gray delta URLs box when there’s 0 delta URLs, it just refreshes the page. The expected behavior would be to take me to the candidate URL page regardless if there’s any delta URLs

### Implementation Considerations

- type your first consideration here

### Deliverable

arst

### Dependencies

depends on

**Comment by CarsonDavis** [comment]
This can be done PI 25.2, however it should be near the beginning.

**Comment by dhanur-sharma** [comment]
The gray delta URLs box on the homepage mimics the functionality as is in production currently. The idea is that the link is present only for collections with non-trivial URL count.

The PR raised for now just updates the condition to include 0, but we can remove the condition entirely if this functionality is not desired in the future as well.
